Parameters:
  DBUsername:
    Type: String
    Default: postgres
    Description: Master database username

  DBPassword:
    Type: String
    NoEcho: true
    Description: Master database password

Resources:
  RcsDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20

Outputs:
  RDSInstanceEndpoint:
    Value: !GetAtt RcsDB.Endpoint.Address
